### ISSUE TITLE
Encoders 

### ISSUE THREAD

**Issue by gedw99** [Just4Ease/graphrpc#7]
I saw that you’re using messagepack and I would like to add bebop to https://github.com/borderlesshq/axon/tree/master/codec

a good write up with links to code about bebop: https://www.reddit.com/r/golang/comments/kj50d9/bebop_encoding_in_go/

I am using Bebop in golang for lots of projects 

here is a the encoder : https://github.com/200sc/bebop

are you interested in PR ,s ??

**Comment by Just4Ease** [comment]
Oh that's fine. You can.
Don't mind my code structure lol. Please proceed

**Comment by gedw99** [comment]
Where to PR and write issues ? 
This repo or the forked one that is more up to date ?

**Comment by Just4Ease** [comment]
Use the forked one.

That one has gone far and has better updates.

**Comment by Just4Ease** [comment]
Right, turning on issues now.

**Comment by gedw99** [comment]
thanks :)

**Comment by gedw99** [comment]
will close here...
